# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:title.html
# relative_permalinks: true

# Setup
url:                 http://catskull.net/reflections
baseurl:             /reflections
paginate:            5

# About/contact
author:
  name:              David DeGraw
  url:               https://twitter.com/davidwdegraw
  email:             bro@catskull.net

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
